version: "3.9"

x-web-variables: &web-variables
  DATABASE_URI: postgresql+psycopg2://postgres:postgres@postgres
  TEST_DATABASE_URI: postgresql+psycopg2://postgres:postgres@test-postgres/game_test

x-pg-variables: &pg-variables
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

x-pg-test-variables: &pg-test-variables
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: game_test

services:
  web:
    build: .
    environment: *web-variables
    ports:
      - 5000:5000
    depends_on:
      - postgres
    volumes:
      - .:/app
    restart: always

  postgres:
    image: postgres:14.1
    environment: *pg-variables
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
  
  test:
    build: .
    command: ["pytest"]
    environment: *web-variables
    depends_on:
      - test-postgres
    volumes:
      - .:/app
    restart: always

  test-postgres:
    image: postgres:14.1
    environment: *pg-test-variables
    ports:
      - 5405:5432
    volumes:
      - /var/lib/postgresql/data

volumes:
  db_data: 
    external: true
